api/api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('dashboard.urls')),
    path('prices/', include('prices.urls')),
    path('admin/', admin.site.urls),
]

api/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='dashboard_index')
]

api/prices/urls.py
from django.urls import path

from . import views

app_name = 'prices'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<slug:ticker>/', views.DetailView.as_view(), name="get_single_crypto"),
]

api/dashboard/models.py
from django.db import models

# Create your models here.

api/prices/models.py
from django.db import models

class Favorite(models.Model):
    ticker = models.CharField(max_length=5)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.ticker

api/dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    context = {}
    return render(request, 'dashboard/dashboard.html', context)

api/prices/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.views.generic import DetailView, ListView

from .models import Favorite

def index(request):
    cryptos = Favorite.objects.all()
    context = {
        'cryptos': cryptos
    }
    return render(request, 'prices/index.html', context)

class IndexView(ListView):
    template_name = 'prices/index.html'
    context_object_name = 'cryptos'

    def get_queryset(self):
        return Favorite.objects.all()

class DetailView(DetailView):
    template_name = 'prices/detail.html'
    context_object_name = 'crypto'

    def get_object(self):
        thing = get_object_or_404(Favorite, ticker__exact=self.kwargs['ticker'])
        return thing

api/dashboard/templates/dashboard/dashboard.html
<h2>Welcome to the dashboard</h2>

<a href="{% url 'prices:index' %}">
    <button type="button">Prices</button>
</a>

api/prices/templates/prices/detail.html
<input type="button" value="Back" onClick="javascript:history.go(-1);">

<h1>{{ crypto.name }}</h1>

api/prices/templates/prices/index.html
<input type="button" value="Back" onClick="javascript:history.go(-1);">

{% if cryptos %}
    <ul>
    {% for crypto in cryptos %}
        <li>
            <a href="{% url 'prices:get_single_crypto' crypto.ticker %}">{{ crypto.name }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>That crypto doesn't exist</p>
{% endif %}